version: '3'
services:
  mysql-member:
    image: mysql
    container_name: mysql-member
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: memberschema
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  mysql-board:
    image: mysql
    container_name: mysql-board
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: boardschema
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

